//! Markdown exporter: export notes as a publishable markdown folder hierarchy.
//!
//! Exports notes and sources to a folder structure suitable for static-site generation.
//! Organizes content hierarchically and generates index files for navigation.

use pkm_core::markdown::note_to_markdown;
use pkm_core::note::Note;
use pkm_core::ports::NoteRepo;
use std::fs;
use std::path::{Path, PathBuf};

/// Configuration for markdown export.
#[derive(Debug, Clone)]
pub struct ExportConfig {
    /// Root directory for export.
    pub output_dir: PathBuf,
    /// Include source information in exported notes.
    pub include_sources: bool,
    /// Include backlinks in exported notes.
    pub include_backlinks: bool,
}

impl ExportConfig {
    pub fn new(output_dir: impl AsRef<Path>) -> Self {
        Self {
            output_dir: output_dir.as_ref().to_path_buf(),
            include_sources: true,
            include_backlinks: true,
        }
    }
}

/// Export a collection of notes to a markdown folder hierarchy.
/// Each note becomes a .md file in the output directory.
/// An index.md file is generated listing all notes.
pub fn export_notes_to_markdown(
    notes: &[Note],
    note_repo: &dyn NoteRepo,
    config: &ExportConfig,
) -> Result<(), String> {
    // Create output directory
    fs::create_dir_all(&config.output_dir)
        .map_err(|e| format!("Failed to create output directory: {}", e))?;

    // Create notes subdirectory
    let notes_dir = config.output_dir.join("notes");
    fs::create_dir_all(&notes_dir)
        .map_err(|e| format!("Failed to create notes directory: {}", e))?;

    let mut index_entries = Vec::new();

    // Export each note
    for note in notes {
        // Get note's blocks from repository
        let note_with_blocks = note_repo
            .get(note.id)
            .map_err(|e| format!("Failed to retrieve note {}: {}", note.id, e))?
            .ok_or_else(|| format!("Note {} not found", note.id))?;

        // Convert note to markdown
        // Note: block retrieval would require access to BlockRepo; for now export just the title
        let blocks = vec![];

        let markdown = note_to_markdown(&note_with_blocks, &blocks);

        // Create safe filename from note title
        let filename =
            sanitize_filename(&note.title).unwrap_or_else(|| format!("note_{}", note.id));
        let filepath = notes_dir.join(format!("{}.md", filename));

        // Write markdown file
        fs::write(&filepath, markdown)
            .map_err(|e| format!("Failed to write note file {}: {}", filename, e))?;

        // Add to index
        let relative_path = format!("notes/{}.md", filename);
        index_entries.push((note.title.clone(), relative_path));
    }

    // Generate index.md
    let index_content = generate_index(&index_entries);
    let index_path = config.output_dir.join("index.md");
    fs::write(&index_path, index_content)
        .map_err(|e| format!("Failed to write index.md: {}", e))?;

    Ok(())
}

/// Generate index.md content from a list of notes.
fn generate_index(entries: &[(String, String)]) -> String {
    let mut content = String::from("# Knowledge Base Index\n\n");
    content.push_str("## Notes\n\n");

    if entries.is_empty() {
        content.push_str("_No notes yet._\n");
    } else {
        for (title, path) in entries {
            content.push_str(&format!("- [{}]({})\n", title, path));
        }
    }

    content.push_str("\n---\n\nGenerated by Rusidian PKM\n");
    content
}

/// Sanitize a filename by replacing unsafe characters.
fn sanitize_filename(name: &str) -> Option<String> {
    if name.is_empty() {
        return None;
    }

    let sanitized = name
        .chars()
        .map(|c| match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '_' | '-' => c,
            ' ' => '-',
            _ => '_',
        })
        .collect::<String>();

    if sanitized.is_empty() {
        None
    } else {
        Some(sanitized)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn sanitize_filename_basic() {
        assert_eq!(sanitize_filename("My Note"), Some("My-Note".to_string()));
        assert_eq!(
            sanitize_filename("Note with special @#$ chars"),
            Some("Note-with-special-___-chars".to_string())
        );
        assert_eq!(sanitize_filename(""), None);
    }

    #[test]
    fn sanitize_filename_alphanumeric() {
        assert_eq!(
            sanitize_filename("SimpleNote123"),
            Some("SimpleNote123".to_string())
        );
    }

    #[test]
    fn generate_index_empty() {
        let entries: Vec<(String, String)> = vec![];
        let content = generate_index(&entries);
        assert!(content.contains("Knowledge Base Index"));
        assert!(content.contains("_No notes yet._"));
    }

    #[test]
    fn generate_index_with_entries() {
        let entries = vec![
            ("First Note".to_string(), "notes/first-note.md".to_string()),
            (
                "Second Note".to_string(),
                "notes/second-note.md".to_string(),
            ),
        ];
        let content = generate_index(&entries);
        assert!(content.contains("First Note"));
        assert!(content.contains("notes/first-note.md"));
        assert!(content.contains("Second Note"));
        assert!(content.contains("notes/second-note.md"));
    }

    #[test]
    fn export_config_creation() {
        let config = ExportConfig::new("/tmp/export");
        assert_eq!(config.output_dir, Path::new("/tmp/export"));
        assert!(config.include_sources);
        assert!(config.include_backlinks);
    }
}
