import { useState } from 'react'
import { AlertCircle, CheckCircle, Clock } from 'lucide-react'

export interface Block {
  id: string
  content: string
  status: 'UserAuthored' | 'RawSource' | 'AiSummary' | 'ExtractedMetadata' | 'InferredLink' | 'Reviewed' | 'UnreviewedSuggestion'
  created_by?: string
}

interface MarkdownWithStatusProps {
  blocks: Block[]
  onReviewBlock?: (blockId: string, accepted: boolean) => void
}

const statusConfig = {
  UserAuthored: { label: 'User', color: 'bg-blue-50', icon: '✍️', style: 'text-blue-700' },
  RawSource: { label: 'Raw Source', color: 'bg-gray-50', icon: '📄', style: 'text-gray-700' },
  AiSummary: { label: 'AI Summary', color: 'bg-amber-50', icon: '🤖', style: 'text-amber-700' },
  ExtractedMetadata: { label: 'Extracted', color: 'bg-purple-50', icon: '🏷️', style: 'text-purple-700' },
  InferredLink: { label: 'Inferred', color: 'bg-green-50', icon: '🔗', style: 'text-green-700' },
  Reviewed: { label: 'Reviewed', color: 'bg-green-50', icon: '✓', style: 'text-green-700' },
  UnreviewedSuggestion: { label: 'Unreviewed', color: 'bg-yellow-50', icon: '⚠️', style: 'text-yellow-700' },
}

export default function MarkdownWithStatus({ blocks, onReviewBlock }: MarkdownWithStatusProps) {
  const [expandedBlockId, setExpandedBlockId] = useState<string | null>(null)
  const [hoveredBlockId, setHoveredBlockId] = useState<string | null>(null)

  const getStatusIcon = (status: Block['status']) => {
    const icons = {
      UserAuthored: <span className="text-blue-600">✍️</span>,
      RawSource: <span className="text-gray-600">📄</span>,
      AiSummary: <span className="text-amber-600">🤖</span>,
      ExtractedMetadata: <span className="text-purple-600">🏷️</span>,
      InferredLink: <span className="text-green-600">🔗</span>,
      Reviewed: <CheckCircle className="w-4 h-4 text-green-600" />,
      UnreviewedSuggestion: <AlertCircle className="w-4 h-4 text-yellow-600" />,
    }
    return icons[status]
  }

  return (
    <div className="space-y-4">
      {blocks.map((block) => {
        const config = statusConfig[block.status]
        const isUnreviewed = block.status === 'UnreviewedSuggestion'
        const isAiSummary = block.status === 'AiSummary'

        return (
          <div
            key={block.id}
            className={`relative rounded-lg transition-all ${
              expandedBlockId === block.id
                ? `${config.color} border-2 border-gray-300 p-4`
                : `${config.color} border border-gray-200 p-4`
            }`}
            onMouseEnter={() => setHoveredBlockId(block.id)}
            onMouseLeave={() => setHoveredBlockId(block.id === expandedBlockId ? block.id : null)}
            onClick={() =>
              setExpandedBlockId(expandedBlockId === block.id ? null : block.id)
            }
          >
            {/* Content with conditional styling */}
            <div className="flex gap-3">
              <div className="flex-shrink-0 flex items-start pt-1">
                {getStatusIcon(block.status)}
              </div>

              <div className="flex-1 min-w-0">
                {/* Unreviewed content gets wavy underline */}
                <p
                  className={`text-gray-800 leading-relaxed ${
                    isUnreviewed
                      ? 'ai-unverified'
                      : isAiSummary
                        ? 'ai-summary'
                        : ''
                  }`}
                >
                  {block.content}
                </p>

                {/* Status badge and info */}
                <div className="flex items-center gap-2 mt-2">
                  <span
                    className={`inline-block px-2 py-1 rounded text-xs font-medium ${config.style} ${config.color}`}
                  >
                    {config.label}
                  </span>
                  {block.created_by && (
                    <span className="text-xs text-gray-500">by {block.created_by}</span>
                  )}
                </div>
              </div>

              {/* Hover indicator */}
              {hoveredBlockId === block.id && isUnreviewed && (
                <div className="flex-shrink-0 text-xs text-yellow-600 cursor-help">
                  ?
                </div>
              )}
            </div>

            {/* Expanded details */}
            {expandedBlockId === block.id && isUnreviewed && (
              <div className="mt-4 pt-4 border-t border-gray-300 space-y-3">
                <div className="text-sm text-gray-700">
                  <p className="font-medium mb-2">AI-generated Content</p>
                  <p className="text-gray-600">
                    This block was generated by an AI agent and hasn't been reviewed yet.
                    Click accept to confirm or dismiss to ignore.
                  </p>
                </div>

                <div className="bg-white rounded p-3 space-y-2">
                  <p className="text-xs font-medium text-gray-700">Block ID: {block.id}</p>
                  <p className="text-xs text-gray-600">Status: {block.status}</p>
                </div>

                <div className="flex gap-2 justify-end">
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      onReviewBlock?.(block.id, false)
                      setExpandedBlockId(null)
                    }}
                    className="px-3 py-1 text-sm bg-gray-200 text-gray-800 rounded hover:bg-gray-300 transition-colors"
                  >
                    Dismiss
                  </button>
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      onReviewBlock?.(block.id, true)
                      setExpandedBlockId(null)
                    }}
                    className="px-3 py-1 text-sm bg-green-600 text-white rounded hover:bg-green-700 transition-colors"
                  >
                    Accept
                  </button>
                </div>
              </div>
            )}

            {expandedBlockId === block.id && isAiSummary && (
              <div className="mt-4 pt-4 border-t border-gray-300">
                <div className="text-sm text-gray-700">
                  <p className="font-medium mb-2">AI Summary</p>
                  <p className="text-gray-600">
                    This content was automatically summarized by an AI system based on source material.
                  </p>
                </div>
              </div>
            )}

            {expandedBlockId === block.id && !isUnreviewed && !isAiSummary && (
              <div className="mt-4 pt-4 border-t border-gray-300">
                <div className="text-sm text-gray-700">
                  <p className="font-medium mb-2">Block Details</p>
                  <p className="text-xs text-gray-600">ID: {block.id}</p>
                  <p className="text-xs text-gray-600">Status: {block.status}</p>
                  {block.created_by && (
                    <p className="text-xs text-gray-600">Created by: {block.created_by}</p>
                  )}
                </div>
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}
